name: Robô Indexador
on:
  schedule:
    - cron: '0 * * * *' # Roda a cada hora (no minuto 0)
  workflow_dispatch: # Permite rodar manualmente pelo botão no GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install axios cheerio
      - name: Executar Crawler
        run: node crawler.js
      - name: Salvar Resultados
        run: |
          git config --global user.name 'Bot-Indexador'
          git config --global user.email 'bot@github.com'
          git add meu_indice.json
          git commit -m "Atualizando índice: $(date)"
          git push
          
